
-- Lecture 02 - DDL, Data Types and ALTER

CREATE DATABASE IF NOT EXISTS COMPANY;

USE COMPANY;


CREATE TABLE EMPLOYEE (
    EMP_ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE,
    SALARY FLOAT
);

DESCRIBE EMPLOYEE;


-- CHAR -> fixed length
-- VARCHAR -> variable length


-- ALTER TABLE

ALTER TABLE EMPLOYEE
ADD COLUMN CITY VARCHAR(30);

ALTER TABLE EMPLOYEE
RENAME COLUMN NAME TO EMP_NAME;

ALTER TABLE EMPLOYEE
MODIFY SALARY DECIMAL(10, 2);


-- change the table name 

RENAME TABLE EMPLOYEE TO EMPLOYEES;

DESCRIBE EMPLOYEES;


-- DELETE -> rows remove, WHERE use kar sakte hain
-- TRUNCATE -> saari rows ek saath remove / ktm tata bye bye

-- DELETE FROM EMPLOYEES WHERE EMP_ID = 1;
-- TRUNCATE TABLE EMPLOYEES;
