-- Lecture 03 - Data Types, Constraints & DML


CREATE DATABASE IF NOT EXISTS COLLEGES;

USE COLLEGES;


-- Common MySQL Data Types
-- Numeric -> INT, BIGINT, FLOAT, DOUBLE, DECIMAL, BOOLEAN
-- String  -> CHAR, VARCHAR, TEXT, ENUM, SET, BLOB
-- Date    -> DATE, DATETIME, TIMESTAMP, TIME, YEAR


CREATE TABLE STUDENT (
    ID INT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    AGE INT CHECK (AGE >= 18),
    EMAIL VARCHAR(100) UNIQUE,
    CITY VARCHAR(30) DEFAULT 'Jaipur',
    CGPA DECIMAL(3, 2)
);


-- INSERT

INSERT INTO STUDENT
VALUES (1, 'GOVIND', 23, 'govind@gmail.com', 'Jaipur', 8.7);

INSERT INTO STUDENT (ID, NAME, AGE, EMAIL, CGPA)
VALUES (2, 'AMAN', 20, 'aman@gmail.com', 8.2);


SELECT * FROM STUDENT;


-- UPDATE

UPDATE STUDENT
SET NAME = 'GOVIND JANGID'
WHERE ID = 1;


-- DELETE

DELETE FROM STUDENT
WHERE ID = 2;


SELECT * FROM STUDENT;
