-- ==========================================
-- Lecture 04 - SELECT, WHERE and Operators
-- ==========================================

CREATE DATABASE IF NOT EXISTS STUDENTSSS;
USE STUDENTSSS;

CREATE TABLE STUDENTS (
    ID INT PRIMARY KEY,
    NAME VARCHAR(50),
    CITY VARCHAR(30),
    CGPA DECIMAL(3, 2)
);

INSERT INTO STUDENTS VALUES
(1, 'GOVIND', 'JAIPUR', 9.5),
(2, 'NAGORI', 'JAIPUR', 9.9),
(3, 'AMAN', 'DELHI', 8.4),
(4, 'RIYA', 'KOTA', 7.8),
(5, 'GAURAV', 'DELHI', 9.0);


SELECT * FROM STUDENTS;

SELECT NAME, CGPA
FROM STUDENTS;


-- WHERE

SELECT *
FROM STUDENTS
WHERE CGPA > 9;


-- Logical operators

SELECT *
FROM STUDENTS
WHERE CITY = 'JAIPUR' AND CGPA > 9;

SELECT *
FROM STUDENTS
WHERE CITY = 'JAIPUR' OR CITY = 'DELHI';

SELECT *
FROM STUDENTS
WHERE NOT CITY = 'JAIPUR';


-- BETWEEN

SELECT *
FROM STUDENTS
WHERE CGPA BETWEEN 9 AND 10;


-- IN

SELECT *
FROM STUDENTS
WHERE CITY IN ('JAIPUR', 'DELHI');


-- LIKE
-- % -> zero ya multiple characters
-- _ -> exactly one character

SELECT * FROM STUDENTS WHERE NAME LIKE 'G%';
SELECT * FROM STUDENTS WHERE NAME LIKE '%GA%';
SELECT * FROM STUDENTS WHERE NAME LIKE '%G';
SELECT * FROM STUDENTS WHERE NAME LIKE '_A%';


-- MySQL REGEXP

SELECT *
FROM STUDENTS
WHERE NAME REGEXP '^G';
