
-- Lecture 07 - SQL JOINs


CREATE DATABASE IF NOT EXISTS COLLEGE_DB;
USE COLLEGE_DB;


CREATE TABLE DEPARTMENT (
    ID INT PRIMARY KEY,
    DEPT_NAME VARCHAR(50),
    DEPT_HEAD VARCHAR(50)
);

CREATE TABLE STUDENT (
    ID INT PRIMARY KEY,
    NAME VARCHAR(50),
    EMAIL VARCHAR(100),
    CITY VARCHAR(30),
    MARKS INT,
    DEPT_ID INT,
    FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENT(ID)
);


INSERT INTO DEPARTMENT VALUES
(1, 'CSE', 'Mr. Sharma'),
(2, 'IT', 'Ms. Jain'),
(3, 'ELECTRICAL', 'Mr. Verma');

INSERT INTO STUDENT VALUES
(1, 'Govind', 'govind@gmail.com', 'Jaipur', 90, 1),
(2, 'Aman', 'aman@gmail.com', 'Delhi', 80, 1),
(3, 'Gourav', 'gourav@gmail.com', 'Jaipur', 88, 2);


-- INNER JOIN -> matching rows

SELECT S.NAME, S.MARKS, D.DEPT_NAME
FROM STUDENT S
INNER JOIN DEPARTMENT D
ON S.DEPT_ID = D.ID;


-- LEFT JOIN -> left ki saari rows

SELECT *
FROM STUDENT S
LEFT JOIN DEPARTMENT D
ON S.DEPT_ID = D.ID;


-- RIGHT JOIN -> right ki saari rows

SELECT *
FROM STUDENT S
RIGHT JOIN DEPARTMENT D
ON S.DEPT_ID = D.ID;


-- MySQL me direct FULL OUTER JOIN nahi hota
-- LEFT + RIGHT ko UNION kar sakte hain

SELECT *
FROM STUDENT S
LEFT JOIN DEPARTMENT D
ON S.DEPT_ID = D.ID

UNION

SELECT *
FROM STUDENT S
RIGHT JOIN DEPARTMENT D
ON S.DEPT_ID = D.ID;


-- CROSS JOIN -> har row ka har row se combination
-- like cross in sets
SELECT S.NAME, D.DEPT_NAME
FROM STUDENT S
CROSS JOIN DEPARTMENT D;


-- SELF JOIN example

CREATE TABLE EMPLOYEE (
    ID INT PRIMARY KEY,
    NAME VARCHAR(50),
    MANAGER_ID INT
);

INSERT INTO EMPLOYEE VALUES
(1, 'Manager', NULL),
(2, 'Aman', 1),
(3, 'nagori', 1);

SELECT
    E.NAME AS EMPLOYEE,
    M.NAME AS MANAGER
FROM EMPLOYEE E
LEFT JOIN EMPLOYEE M
ON E.MANAGER_ID = M.ID;
